#
# This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit
  dockerimage:
    name: Docker Build and Push
    needs: [buildandtest]
    uses: StanfordBDHG/.github/.github/workflows/docker-build-and-push.yml@v2
    with:
      imageName: stanfordbdhg/engagehfwebfrontend
      environment: package
    permissions:
      contents: read
      packages: write
  deploy:
    name: Deploy Firebase Project
    uses: StanfordBDHG/.github/.github/workflows/firebase-deploy.yml@v2
    needs: [buildandtest]
    permissions:
      contents: read
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
