#
# This source file is part of the Stanford Biodesign Digital Health Next.js Template open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      checks: write
  dockerimage:
    name: Docker Build and Push
    uses: StanfordBDHG/.github/.github/workflows/docker-build-and-push.yml@v2
    with:
      imageName: stanfordbdhg/engagehffrontend
      environment: package
    permissions:
      contents: read
      packages: write
