#
# This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Production Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deployment:
    name: Production Deployment
    uses: ./.github/workflows/deployment.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    secrets: inherit
    with:
      environment: production
